---
language: rust
script:
- "./_test/check-exercises.sh"
- "./bin/fetch-configlet"
- "./bin/configlet ."
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
