[package]
name = "exercise"
version = "1.4.0"
description = "An utility for creating or updating the exercises on the Exercism Rust track"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
failure_derive = "0.1.3"
flate2 = "1.0"
lazy_static = "1.1.0"
serde_json = "1.0.26"
tar = "0.4.16"
toml = "0.4"
uuid = { version = "0.7", features = ["v4"] }

[dependencies.git2]    
version = "0.8.0"    
default-features = false    
    
[dependencies.reqwest]    
version = "0.9.8"    
default-features = false    
features = ["rustls-tls"]   
